### ISSUE TITLE
Docker内无法访问控制台

### ISSUE THREAD

**Issue by MeowRay** [snail007/goproxy#420]
debian10 centos8均试过
docker-compose
```
version: '3'
services:
  goproxy:
    restart: always
    image: snail007/goproxy:v10.0
    ports:
     - "33080:33080"
    command:
     - http
     - -p
     - :33080
```
和Example中的
`docker run --rm -it -p 8080:33080 snail007/goproxy http -p :33080`
均出现如图情况

![image](https://user-images.githubusercontent.com/29674595/107138177-de6cc280-694d-11eb-83e4-4bc553d7009c.png)

![image](https://user-images.githubusercontent.com/29674595/107138203-1247e800-694e-11eb-905d-938e94711118.png)
